version: '3.7'

services:
  db:
    image: postgres:14
    container_name: audio_db
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  audio_converter:
    build:
      context: .
    container_name: audio_converter
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: sh -c "alembic upgrade head && gunicorn audio_converter.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8888:8000
